#!/bin/bash

# generated by AI

# ==========================================
# Configuration variables
# ==========================================
APP_NAME="OSXRDP.app"
UNINS_APP_NAME="OSXRDPUninstaller.app"
INSTALL_FOLDER_NAME="osxrdp"
PKG_ID="com.byungho.osxrdp.setup"
VERSION="2.0.5"

# Filename settings
COMPONENT_PKG="osxrdp_component.pkg"
OUTPUT_PKG="osxrdp_installer_v${VERSION}.pkg"
DIST_XML="distribution.xml"

# Path settings
ROOT_DIR=$(pwd)
PAYLOAD_DIR="$ROOT_DIR/payload"
SOURCE_DIR="$ROOT_DIR/source"
SCRIPTS_DIR="$ROOT_DIR/scripts"

# [Added] Signing and notarization settings
# Name verified via 'security find-identity -v -p installer' in terminal ("Developer ID Installer: Name (TeamID)")
SIGNING_IDENTITY="Developer ID Installer: BYEONGHO KIM (33X7M69J4B)"

# Profile name created via 'xcrun notarytool store-credentials' in terminal
NOTARY_KEYCHAIN_PROFILE="AC_PASSWORD"

# ==========================================
# 0. Pre-check
# ==========================================
if [ ! -f "$DIST_XML" ]; then
    echo "❌ Error: $DIST_XML not found in current directory."
    exit 1
fi

echo "=== [1/6] Cleaning up old build files ==="
rm -rf "$PAYLOAD_DIR"
rm -f "$COMPONENT_PKG" "$OUTPUT_PKG"

# ==========================================
# 1. Build payload
# ==========================================
echo "=== [2/6] Staging files into Payload ==="

mkdir -p "$PAYLOAD_DIR/Applications/$INSTALL_FOLDER_NAME"
mkdir -p "$PAYLOAD_DIR/Library/LaunchDaemons"
mkdir -p "$PAYLOAD_DIR/Library/LaunchAgents"
mkdir -p "$PAYLOAD_DIR/etc/xrdp"
mkdir -p "$PAYLOAD_DIR/etc/osxrdp"
mkdir -p "$PAYLOAD_DIR/usr/local/lib/xrdp"
mkdir -p "$PAYLOAD_DIR/usr/local/share/xrdp"

# Copy app (assumed already signed)
if [ -d "$SOURCE_DIR/$APP_NAME" ]; then
    cp -R "$SOURCE_DIR/$APP_NAME" "$PAYLOAD_DIR/Applications/$INSTALL_FOLDER_NAME/"
else
    echo "❌ Error: '$APP_NAME' not found in source directory."
    exit 1
fi

if [ -d "$SOURCE_DIR/$UNINS_APP_NAME" ]; then
    cp -R "$SOURCE_DIR/$UNINS_APP_NAME" "$PAYLOAD_DIR/Applications/$INSTALL_FOLDER_NAME/"
else
    echo "❌ Error: '$UNINS_APP_NAME' not found in source directory."
    exit 1
fi
# Copy other files
cp "$SOURCE_DIR/com.byungho.osxrdp.plist" "$PAYLOAD_DIR/Library/LaunchDaemons/"
cp "$SOURCE_DIR/com.byungho.osxrdp.sessionmanager.plist" "$PAYLOAD_DIR/Library/LaunchDaemons/"
cp "$SOURCE_DIR/com.byungho.osxrdp.lockscreen.plist" "$PAYLOAD_DIR/Library/LaunchAgents/"

if [ -d "$SOURCE_DIR/config" ]; then
    cp -R "$SOURCE_DIR/config/"* "$PAYLOAD_DIR/etc/xrdp/"
fi

if [ -d "$SOURCE_DIR/log" ]; then
    cp -R "$SOURCE_DIR/log/"* "$PAYLOAD_DIR/etc/osxrdp/"
fi

cp "$SOURCE_DIR/module/libosxup.dylib" "$PAYLOAD_DIR/usr/local/lib/xrdp"
cp "$SOURCE_DIR/resources/"* "$PAYLOAD_DIR/usr/local/share/xrdp"

# Set permissions
echo "=== [3/6] Setting permissions ==="
sudo chown -R root:wheel "$PAYLOAD_DIR"
sudo chmod 755 "$PAYLOAD_DIR/Applications/$INSTALL_FOLDER_NAME"
sudo chmod 755 "$PAYLOAD_DIR/usr/local/lib/xrdp"
sudo chmod 755 "$PAYLOAD_DIR/usr/local/share/xrdp"
sudo chmod 755 "$SCRIPTS_DIR/postinstall"

# ==========================================
# 2. Build component package (pkgbuild)
# ==========================================
echo "=== [4/6] Building Component Package ==="

pkgbuild --root "$PAYLOAD_DIR" \
         --install-location "/" \
         --scripts "$SCRIPTS_DIR" \
         --identifier "$PKG_ID" \
         --version "$VERSION" \
         "$COMPONENT_PKG"

# ==========================================
# 3. Build and sign final product package (productbuild)
# ==========================================
echo "=== [5/6] Building & Signing Product Package ==="

# Build and sign simultaneously using the --sign option.
productbuild --distribution "$DIST_XML" \
             --package-path . \
             --sign "$SIGNING_IDENTITY" \
             "$OUTPUT_PKG"

if [ $? -ne 0 ]; then
    echo "❌ Error: Product build or signing failed."
    exit 1
fi

# ==========================================
# 4. Notarization and Stapling
# ==========================================
echo "=== [6/6] Notarizing Package ==="

echo "📤 Uploading to Apple Notary Service... (This may take a while)"
xcrun notarytool submit "$OUTPUT_PKG" \
                 --keychain-profile "$NOTARY_KEYCHAIN_PROFILE" \
                 --wait

if [ $? -eq 0 ]; then
    echo "✅ Notarization Succeeded!"
    
    echo "📎 Stapling the ticket to the package..."
    xcrun stapler staple "$OUTPUT_PKG"
    
    echo "🎉 All Done! Final Package: $OUTPUT_PKG"
else
    echo "❌ Notarization Failed. Check the log above."
    exit 1
fi

# Clean up temporary files
rm -f "$COMPONENT_PKG"
sudo rm -rf "$PAYLOAD_DIR"
