//
//  CJKHelper.m
//  OSXRDP
//
//  Created by byungho on 5/16/26.
//

// idea from kawa https://github.com/hatashiro/kawa/pull/12
// codes generated by AI

#import "CJKHelper.h"
#import "InputSourceSelection.h"

#import <ApplicationServices/ApplicationServices.h>
#include <stdlib.h>

static NSString *const kSymbolicHotKeysDomain = @"com.apple.symbolichotkeys";
static NSString *const kAppleSymbolicHotKeys = @"AppleSymbolicHotKeys";
static NSString *const kPreviousInputSourceHotKeyID = @"60";
static const NSTimeInterval kSwitchTimeout = 0.200;
static const NSTimeInterval kSwitchRetryTime = 0.100;
static const int64_t kPollIntervalNs = 10 * NSEC_PER_MSEC;
static TISInputSourceRef gLastCJKVInputSource = NULL;

typedef struct {
    CGKeyCode keyCode;
    CGEventFlags flags;
} PreviousInputSourceHotkey;

typedef struct {
    CGEventFlags flag;
    CGKeyCode keyCode;
} ModifierKeyMapping;

static BOOL InputSourceIsEqual(TISInputSourceRef lhs, TISInputSourceRef rhs)
{
    if (lhs == NULL || rhs == NULL) {
        return NO;
    }

    if (CFEqual(lhs, rhs)) {
        return YES;
    }

    CFTypeRef lhsIDRef =
        TISGetInputSourceProperty(lhs, kTISPropertyInputSourceID);
    CFTypeRef rhsIDRef =
        TISGetInputSourceProperty(rhs, kTISPropertyInputSourceID);

    if (lhsIDRef == NULL || rhsIDRef == NULL) {
        return NO;
    }

    if (CFGetTypeID(lhsIDRef) != CFStringGetTypeID() ||
        CFGetTypeID(rhsIDRef) != CFStringGetTypeID()) {
        return NO;
    }

    return CFStringCompare((CFStringRef)lhsIDRef,
                           (CFStringRef)rhsIDRef,
                           0) == kCFCompareEqualTo;
}

static BOOL InputSourceHasLanguage(TISInputSourceRef source,
                                   CFStringRef languageCode,
                                   BOOL allowPrefix)
{
    CFTypeRef languagesRef = TISGetInputSourceProperty(source, kTISPropertyInputSourceLanguages);

    if (languagesRef == NULL ||
        CFGetTypeID(languagesRef) != CFArrayGetTypeID()) {
        return NO;
    }

    CFArrayRef languages = (CFArrayRef)languagesRef;
    CFIndex count = CFArrayGetCount(languages);

    for (CFIndex i = 0; i < count; i++) {
        CFTypeRef item = CFArrayGetValueAtIndex(languages, i);
        if (item == NULL ||
            CFGetTypeID(item) != CFStringGetTypeID()) {
            continue;
        }

        CFStringRef language = (CFStringRef)item;
        if (CFStringCompare(language, languageCode, 0) == kCFCompareEqualTo) {
            return YES;
        }

        if (allowPrefix && CFStringHasPrefix(language, languageCode)) {
            return YES;
        }
    }

    return NO;
}

static BOOL InputSourceIsCJKV(TISInputSourceRef source)
{
    if (source == NULL) {
        return NO;
    }

    return InputSourceHasLanguage(source, CFSTR("ko"), NO) || // korean
           InputSourceHasLanguage(source, CFSTR("ja"), NO) || // japanese
           InputSourceHasLanguage(source, CFSTR("vi"), NO) || // vietnamese
           InputSourceHasLanguage(source, CFSTR("zh"), YES);  // chinese (traditional, simplified)
}

static CFArrayRef CopySelectableKeyboardInputSources(void)
{
    const void *keys[] = {
        kTISPropertyInputSourceCategory,
        kTISPropertyInputSourceIsSelectCapable
    };

    const void *values[] = {
        kTISCategoryKeyboardInputSource,
        kCFBooleanTrue
    };

    CFDictionaryRef filter =
        CFDictionaryCreate(kCFAllocatorDefault,
                           keys,
                           values,
                           2,
                           &kCFTypeDictionaryKeyCallBacks,
                           &kCFTypeDictionaryValueCallBacks);

    if (filter == NULL) {
        return NULL;
    }

    CFArrayRef inputSources =
        TISCreateInputSourceList(filter, false);

    CFRelease(filter);
    return inputSources;
}

static CFIndex FindInputSourceIndex(CFArrayRef inputSources,
                                    TISInputSourceRef targetSource)
{
    if (inputSources == NULL || targetSource == NULL) {
        return -1;
    }

    CFIndex count = CFArrayGetCount(inputSources);
    for (CFIndex i = 0; i < count; i++) {
        TISInputSourceRef source =
            (TISInputSourceRef)CFArrayGetValueAtIndex(inputSources, i);

        if (InputSourceIsEqual(source, targetSource)) {
            return i;
        }
    }

    return -1;
}

static TISInputSourceRef CopyInputSourceAtIndex(CFArrayRef inputSources,
                                                CFIndex index)
{
    if (inputSources == NULL ||
        index < 0 ||
        index >= CFArrayGetCount(inputSources)) {
        return NULL;
    }

    TISInputSourceRef source =
        (TISInputSourceRef)CFArrayGetValueAtIndex(inputSources, index);

    if (source != NULL) {
        CFRetain(source);
    }

    return source;
}

static TISInputSourceRef CopyToggleInputSource(CFArrayRef inputSources,
                                               TISInputSourceRef currentSource,
                                               TISInputSourceRef preferredCJKVSource)
{
    if (inputSources == NULL) {
        return NULL;
    }

    CFIndex count = CFArrayGetCount(inputSources);
    if (count <= 0) {
        return NULL;
    }

    CFIndex currentIndex = FindInputSourceIndex(inputSources, currentSource);
    if (currentIndex < 0) {
        NSLog(@"[IME] Current input source not found. Fallback to a CJKV source.");
    }

    CFIndex preferredCJKVIndex =
        FindInputSourceIndex(inputSources, preferredCJKVSource);
    bool *isCJKV = (bool *)calloc((size_t)count, sizeof(bool));
    if (isCJKV == NULL) {
        return NULL;
    }

    for (CFIndex i = 0; i < count; i++) {
        TISInputSourceRef source =
            (TISInputSourceRef)CFArrayGetValueAtIndex(inputSources, i);
        isCJKV[i] = InputSourceIsCJKV(source);
    }

    int targetIndex = InputSourceSelectionTargetIndex(
        isCJKV,
        (size_t)count,
        (int)currentIndex,
        (int)preferredCJKVIndex);
    free(isCJKV);

    return CopyInputSourceAtIndex(inputSources, targetIndex);
}

static TISInputSourceRef CopyFirstNonCJKVInputSource(CFArrayRef inputSources)
{
    if (inputSources == NULL) {
        return NULL;
    }

    CFIndex count = CFArrayGetCount(inputSources);
    for (CFIndex i = 0; i < count; i++) {
        TISInputSourceRef source =
            (TISInputSourceRef)CFArrayGetValueAtIndex(inputSources, i);
        if (source != NULL && !InputSourceIsCJKV(source)) {
            CFRetain(source);
            return source;
        }
    }
    return NULL;
}

static BOOL ReadPreviousInputSourceHotkey(PreviousInputSourceHotkey *outHotkey)
{
    if (outHotkey == NULL) {
        return NO;
    }

    NSDictionary *domain =
        [[NSUserDefaults standardUserDefaults]
            persistentDomainForName:kSymbolicHotKeysDomain];

    if (![domain isKindOfClass:[NSDictionary class]]) {
        return NO;
    }

    id allHotkeysObject = domain[kAppleSymbolicHotKeys];
    if (![allHotkeysObject isKindOfClass:[NSDictionary class]]) {
        return NO;
    }

    NSDictionary *allHotkeys = (NSDictionary *)allHotkeysObject;
    id hotkeyObject = allHotkeys[kPreviousInputSourceHotKeyID];
    if (![hotkeyObject isKindOfClass:[NSDictionary class]]) {
        return NO;
    }

    NSDictionary *hotkey = (NSDictionary *)hotkeyObject;
    NSNumber *enabled = hotkey[@"enabled"];
    if (![enabled isKindOfClass:[NSNumber class]] ||
        enabled.boolValue == NO) {
        return NO;
    }

    id valueObject = hotkey[@"value"];
    if (![valueObject isKindOfClass:[NSDictionary class]]) {
        return NO;
    }

    NSDictionary *value = (NSDictionary *)valueObject;
    id parametersObject = value[@"parameters"];
    if (![parametersObject isKindOfClass:[NSArray class]]) {
        return NO;
    }

    NSArray *parameters = (NSArray *)parametersObject;
    if (parameters.count < 3) {
        return NO;
    }

    NSNumber *keyCodeNumber = parameters[1];
    NSNumber *flagsNumber = parameters[2];

    if (![keyCodeNumber isKindOfClass:[NSNumber class]] ||
        ![flagsNumber isKindOfClass:[NSNumber class]]) {
        return NO;
    }

    outHotkey->keyCode = (CGKeyCode)keyCodeNumber.unsignedShortValue;
    outHotkey->flags = (CGEventFlags)flagsNumber.unsignedLongLongValue;

    return YES;
}

static size_t CollectModifierKeyMappings(CGEventFlags flags,
                                         ModifierKeyMapping *outMappings,
                                         size_t capacity)
{
    static const ModifierKeyMapping mappings[] = {
        { kCGEventFlagMaskControl, kVK_Control },
        { kCGEventFlagMaskAlternate, kVK_Option },
        { kCGEventFlagMaskShift, kVK_Shift },
        { kCGEventFlagMaskCommand, kVK_Command }
    };

    size_t count = 0;

    for (size_t i = 0; i < sizeof(mappings) / sizeof(mappings[0]); i++) {
        if ((flags & mappings[i].flag) == 0) {
            continue;
        }

        if (count >= capacity) {
            break;
        }

        outMappings[count++] = mappings[i];
    }

    return count;
}

static BOOL PostKeyboardEvent(CGEventSourceRef source,
                              CGKeyCode keyCode,
                              BOOL keyDown,
                              CGEventFlags flags)
{
    CGEventRef event =
        CGEventCreateKeyboardEvent(source, keyCode, keyDown);

    if (event == NULL) {
        return NO;
    }

    CGEventSetFlags(event, flags);
    CGEventPost(kCGSessionEventTap, event);

    CFRelease(event);
    return YES;
}

static BOOL PostPreviousInputSourceShortcut(const PreviousInputSourceHotkey *hotkey)
{
    if (hotkey == NULL) {
        return NO;
    }

    CGEventSourceRef source = [CJKHelper sharedKeyboardEventSource];

    if (source == NULL) {
        return NO;
    }

    ModifierKeyMapping modifiers[4] = {0};
    size_t modifierCount =
        CollectModifierKeyMappings(hotkey->flags,
                                   modifiers,
                                   sizeof(modifiers) / sizeof(modifiers[0]));

    CGEventFlags flags = 0;

    for (size_t i = 0; i < modifierCount; i++) {
        flags |= modifiers[i].flag;

        if (!PostKeyboardEvent(source,
                               modifiers[i].keyCode,
                               YES,
                               flags)) {
            return NO;
        }
    }

    if (!PostKeyboardEvent(source, hotkey->keyCode, YES, hotkey->flags) ||
        !PostKeyboardEvent(source, hotkey->keyCode, NO, hotkey->flags)) {
        return NO;
    }

    for (size_t i = modifierCount; i > 0; i--) {
        ModifierKeyMapping mapping = modifiers[i - 1];
        flags &= ~mapping.flag;

        if (!PostKeyboardEvent(source,
                               mapping.keyCode,
                               NO,
                               flags)) {
            return NO;
        }
    }

    return YES;
}

static NSString *InputSourceID(TISInputSourceRef source)
{
    if (source == NULL) return @"";
    CFTypeRef value = TISGetInputSourceProperty(source, kTISPropertyInputSourceID);
    if (value == NULL || CFGetTypeID(value) != CFStringGetTypeID()) return @"";
    return [(__bridge NSString *)value copy];
}

static NSString *CurrentInputSourceID(void)
{
    TISInputSourceRef current = TISCopyCurrentKeyboardInputSource();
    if (current == NULL) return @"";
    NSString *sourceID = InputSourceID(current);
    CFRelease(current);
    return sourceID;
}

@implementation CJKHelper

+ (CGEventSourceRef)sharedKeyboardEventSource
{
    static CGEventSourceRef source = NULL;
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        source = CGEventSourceCreate(kCGEventSourceStateCombinedSessionState);
    });
    return source;
}

+ (void)selectNextInputSourceWithWorkaround:(CJKInputSourceCompletion)completion
{
    NSAssert([NSThread isMainThread],
             @"CJKHelper must be called on the main thread.");

    CFArrayRef inputSources = CopySelectableKeyboardInputSources();
    if (inputSources == NULL) {
        NSLog(@"[CJKHelper] Failed to get input source list.");
        completion(NO, @"", CurrentInputSourceID(), 0);
        return;
    }

    TISInputSourceRef currentSource = TISCopyCurrentKeyboardInputSource();
    if (currentSource == NULL) {
        NSLog(@"[CJKHelper] Failed to get current input source.");
        CFRelease(inputSources);
        completion(NO, @"", @"", 0);
        return;
    }

    if (InputSourceIsCJKV(currentSource)) {
        if (gLastCJKVInputSource != NULL) {
            CFRelease(gLastCJKVInputSource);
        }
        gLastCJKVInputSource =
            (TISInputSourceRef)CFRetain(currentSource);
    }

    TISInputSourceRef nextSource =
        CopyToggleInputSource(inputSources,
                              currentSource,
                              gLastCJKVInputSource);

    CFRelease(currentSource);

    if (nextSource == NULL) {
        NSLog(@"[CJKHelper] No selectable input sources found.");
        CFRelease(inputSources);
        completion(NO, @"", CurrentInputSourceID(), 0);
        return;
    }

    NSString *targetID = InputSourceID(nextSource);
    BOOL targetIsCJKV = InputSourceIsCJKV(nextSource);
    TISInputSourceRef retryTargetSource =
        (TISInputSourceRef)CFRetain(nextSource);
    PreviousInputSourceHotkey hotkey = {0};
    BOOL canRetryShortcut = NO;

    // Selecting the target first puts it into the input-source history. For
    // CJKV sources, bounce through a non-CJKV source and return via the system
    // "previous input source" shortcut.
    OSStatus directStatus = TISSelectInputSource(nextSource);
    if (directStatus != noErr) {
        NSLog(@"[CJKHelper] direct select failed target=%@ status=%d",
              targetID, (int)directStatus);
    }
    if (targetIsCJKV && directStatus == noErr) {
        TISInputSourceRef nonCJKV = CopyFirstNonCJKVInputSource(inputSources);
        if (nonCJKV != NULL && ReadPreviousInputSourceHotkey(&hotkey)) {
            if (TISSelectInputSource(nonCJKV) == noErr) {
                canRetryShortcut = YES;
                BOOL posted = PostPreviousInputSourceShortcut(&hotkey);
                NSLog(@"[CJKHelper] workaround target=%@ initial_posted=%d",
                      targetID, posted);
            }
            CFRelease(nonCJKV);
        }
        else {
            NSLog(@"[CJKHelper] CJKV workaround unavailable; verifying direct selection");
            if (nonCJKV != NULL) CFRelease(nonCJKV);
        }
    }

    CFRelease(nextSource);
    CFRelease(inputSources);

    CFAbsoluteTime startedAt = CFAbsoluteTimeGetCurrent();
    __block BOOL retried = NO;
    __block void (^poll)(void) = nil;
    poll = ^{
        NSString *actualID = CurrentInputSourceID();
        NSTimeInterval elapsed = CFAbsoluteTimeGetCurrent() - startedAt;
        if ([actualID isEqualToString:targetID]) {
            CFRelease(retryTargetSource);
            completion(YES, targetID, actualID, elapsed);
            poll = nil;
            return;
        }
        if (elapsed >= kSwitchTimeout) {
            NSLog(@"[CJKHelper] timeout target=%@ actual=%@ elapsed=%.3f retried=%d",
                  targetID, actualID, elapsed, retried);
            CFRelease(retryTargetSource);
            completion(NO, targetID, actualID, elapsed);
            poll = nil;
            return;
        }
        if (!retried && elapsed >= kSwitchRetryTime) {
            retried = YES;
            if (canRetryShortcut) {
                BOOL posted = PostPreviousInputSourceShortcut(&hotkey);
                NSLog(@"[CJKHelper] retry shortcut target=%@ elapsed=%.3f posted=%d",
                      targetID, elapsed, posted);
            }
            else {
                OSStatus retryStatus = TISSelectInputSource(retryTargetSource);
                NSLog(@"[CJKHelper] retry direct target=%@ elapsed=%.3f status=%d",
                      targetID, elapsed, (int)retryStatus);
            }
        }
        dispatch_after(dispatch_time(DISPATCH_TIME_NOW, kPollIntervalNs),
                       dispatch_get_main_queue(), poll);
    };
    poll();
}

@end
