//
//  CJKHelper.m
//  OSXRDP
//
//  Created by byungho on 5/16/26.
//

// idea from kawa https://github.com/hatashiro/kawa/pull/12
// codes generated by AI

#import "CJKHelper.h"

#import <ApplicationServices/ApplicationServices.h>

static NSString *const kSymbolicHotKeysDomain = @"com.apple.symbolichotkeys";
static NSString *const kAppleSymbolicHotKeys = @"AppleSymbolicHotKeys";
static NSString *const kNextInputSourceHotKeyID = @"61";
static const OSStatus kInputSourceError = -1;

typedef struct {
    CGKeyCode keyCode;
    CGEventFlags flags;
} NextInputSourceHotkey;

typedef struct {
    CGEventFlags flag;
    CGKeyCode keyCode;
} ModifierKeyMapping;

static BOOL InputSourceIsEqual(TISInputSourceRef lhs, TISInputSourceRef rhs)
{
    if (lhs == NULL || rhs == NULL) {
        return NO;
    }

    if (CFEqual(lhs, rhs)) {
        return YES;
    }

    CFTypeRef lhsIDRef =
        TISGetInputSourceProperty(lhs, kTISPropertyInputSourceID);
    CFTypeRef rhsIDRef =
        TISGetInputSourceProperty(rhs, kTISPropertyInputSourceID);

    if (lhsIDRef == NULL || rhsIDRef == NULL) {
        return NO;
    }

    if (CFGetTypeID(lhsIDRef) != CFStringGetTypeID() ||
        CFGetTypeID(rhsIDRef) != CFStringGetTypeID()) {
        return NO;
    }

    return CFStringCompare((CFStringRef)lhsIDRef,
                           (CFStringRef)rhsIDRef,
                           0) == kCFCompareEqualTo;
}

static BOOL InputSourceHasLanguage(TISInputSourceRef source,
                                   CFStringRef languageCode,
                                   BOOL allowPrefix)
{
    CFTypeRef languagesRef = TISGetInputSourceProperty(source, kTISPropertyInputSourceLanguages);

    if (languagesRef == NULL ||
        CFGetTypeID(languagesRef) != CFArrayGetTypeID()) {
        return NO;
    }

    CFArrayRef languages = (CFArrayRef)languagesRef;
    CFIndex count = CFArrayGetCount(languages);

    for (CFIndex i = 0; i < count; i++) {
        CFTypeRef item = CFArrayGetValueAtIndex(languages, i);
        if (item == NULL ||
            CFGetTypeID(item) != CFStringGetTypeID()) {
            continue;
        }

        CFStringRef language = (CFStringRef)item;
        if (CFStringCompare(language, languageCode, 0) == kCFCompareEqualTo) {
            return YES;
        }

        if (allowPrefix && CFStringHasPrefix(language, languageCode)) {
            return YES;
        }
    }

    return NO;
}

static BOOL InputSourceIsCJKV(TISInputSourceRef source)
{
    if (source == NULL) {
        return NO;
    }

    return InputSourceHasLanguage(source, CFSTR("ko"), NO) || // korean
           InputSourceHasLanguage(source, CFSTR("ja"), NO) || // japanese
           InputSourceHasLanguage(source, CFSTR("vi"), NO) || // vietnamese
           InputSourceHasLanguage(source, CFSTR("zh"), YES);  // chinese (traditional, simplified)
}

static CFArrayRef CopySelectableKeyboardInputSources(void)
{
    const void *keys[] = {
        kTISPropertyInputSourceCategory,
        kTISPropertyInputSourceIsSelectCapable
    };

    const void *values[] = {
        kTISCategoryKeyboardInputSource,
        kCFBooleanTrue
    };

    CFDictionaryRef filter =
        CFDictionaryCreate(kCFAllocatorDefault,
                           keys,
                           values,
                           2,
                           &kCFTypeDictionaryKeyCallBacks,
                           &kCFTypeDictionaryValueCallBacks);

    if (filter == NULL) {
        return NULL;
    }

    CFArrayRef inputSources =
        TISCreateInputSourceList(filter, false);

    CFRelease(filter);
    return inputSources;
}

static CFIndex FindInputSourceIndex(CFArrayRef inputSources,
                                    TISInputSourceRef targetSource)
{
    if (inputSources == NULL || targetSource == NULL) {
        return -1;
    }

    CFIndex count = CFArrayGetCount(inputSources);
    for (CFIndex i = 0; i < count; i++) {
        TISInputSourceRef source =
            (TISInputSourceRef)CFArrayGetValueAtIndex(inputSources, i);

        if (InputSourceIsEqual(source, targetSource)) {
            return i;
        }
    }

    return -1;
}

static TISInputSourceRef CopyInputSourceAtIndex(CFArrayRef inputSources,
                                                CFIndex index)
{
    if (inputSources == NULL ||
        index < 0 ||
        index >= CFArrayGetCount(inputSources)) {
        return NULL;
    }

    TISInputSourceRef source =
        (TISInputSourceRef)CFArrayGetValueAtIndex(inputSources, index);

    if (source != NULL) {
        CFRetain(source);
    }

    return source;
}

static TISInputSourceRef CopyNextInputSource(CFArrayRef inputSources,
                                             TISInputSourceRef currentSource)
{
    if (inputSources == NULL) {
        return NULL;
    }

    CFIndex count = CFArrayGetCount(inputSources);
    if (count <= 0) {
        return NULL;
    }

    CFIndex currentIndex = FindInputSourceIndex(inputSources, currentSource);
    CFIndex nextIndex = currentIndex < 0 ? 0 : (currentIndex + 1) % count;

    if (currentIndex < 0) {
        NSLog(@"[IME] Current input source not found. Fallback to first source.");
    }

    return CopyInputSourceAtIndex(inputSources, nextIndex);
}

static TISInputSourceRef CopyPreviousInputSource(CFArrayRef inputSources,
                                                 TISInputSourceRef targetSource)
{
    if (inputSources == NULL) {
        return NULL;
    }

    CFIndex count = CFArrayGetCount(inputSources);
    CFIndex targetIndex = FindInputSourceIndex(inputSources, targetSource);

    if (count <= 0 || targetIndex < 0) {
        return NULL;
    }

    CFIndex previousIndex = (targetIndex - 1 + count) % count;
    return CopyInputSourceAtIndex(inputSources, previousIndex);
}

static BOOL ReadNextInputSourceHotkey(NextInputSourceHotkey *outHotkey)
{
    if (outHotkey == NULL) {
        return NO;
    }

    NSDictionary *domain =
        [[NSUserDefaults standardUserDefaults]
            persistentDomainForName:kSymbolicHotKeysDomain];

    if (![domain isKindOfClass:[NSDictionary class]]) {
        return NO;
    }

    id allHotkeysObject = domain[kAppleSymbolicHotKeys];
    if (![allHotkeysObject isKindOfClass:[NSDictionary class]]) {
        return NO;
    }

    NSDictionary *allHotkeys = (NSDictionary *)allHotkeysObject;
    id hotkeyObject = allHotkeys[kNextInputSourceHotKeyID];
    if (![hotkeyObject isKindOfClass:[NSDictionary class]]) {
        return NO;
    }

    NSDictionary *hotkey = (NSDictionary *)hotkeyObject;
    NSNumber *enabled = hotkey[@"enabled"];
    if (![enabled isKindOfClass:[NSNumber class]] ||
        enabled.boolValue == NO) {
        return NO;
    }

    id valueObject = hotkey[@"value"];
    if (![valueObject isKindOfClass:[NSDictionary class]]) {
        return NO;
    }

    NSDictionary *value = (NSDictionary *)valueObject;
    id parametersObject = value[@"parameters"];
    if (![parametersObject isKindOfClass:[NSArray class]]) {
        return NO;
    }

    NSArray *parameters = (NSArray *)parametersObject;
    if (parameters.count < 3) {
        return NO;
    }

    NSNumber *keyCodeNumber = parameters[1];
    NSNumber *flagsNumber = parameters[2];

    if (![keyCodeNumber isKindOfClass:[NSNumber class]] ||
        ![flagsNumber isKindOfClass:[NSNumber class]]) {
        return NO;
    }

    outHotkey->keyCode = (CGKeyCode)keyCodeNumber.unsignedShortValue;
    outHotkey->flags = (CGEventFlags)flagsNumber.unsignedLongLongValue;

    return YES;
}

static size_t CollectModifierKeyMappings(CGEventFlags flags,
                                         ModifierKeyMapping *outMappings,
                                         size_t capacity)
{
    static const ModifierKeyMapping mappings[] = {
        { kCGEventFlagMaskControl, kVK_Control },
        { kCGEventFlagMaskAlternate, kVK_Option },
        { kCGEventFlagMaskShift, kVK_Shift },
        { kCGEventFlagMaskCommand, kVK_Command }
    };

    size_t count = 0;

    for (size_t i = 0; i < sizeof(mappings) / sizeof(mappings[0]); i++) {
        if ((flags & mappings[i].flag) == 0) {
            continue;
        }

        if (count >= capacity) {
            break;
        }

        outMappings[count++] = mappings[i];
    }

    return count;
}

static BOOL PostKeyboardEvent(CGEventSourceRef source,
                              CGKeyCode keyCode,
                              BOOL keyDown,
                              CGEventFlags flags)
{
    CGEventRef event =
        CGEventCreateKeyboardEvent(source, keyCode, keyDown);

    if (event == NULL) {
        return NO;
    }

    CGEventSetFlags(event, flags);
    CGEventPost(kCGHIDEventTap, event);

    CFRelease(event);
    return YES;
}

static BOOL PostNextInputSourceShortcut(const NextInputSourceHotkey *hotkey)
{
    if (hotkey == NULL) {
        return NO;
    }

    CGEventSourceRef source =
        CGEventSourceCreate(kCGEventSourceStateHIDSystemState);

    if (source == NULL) {
        return NO;
    }

    ModifierKeyMapping modifiers[4] = {0};
    size_t modifierCount =
        CollectModifierKeyMappings(hotkey->flags,
                                   modifiers,
                                   sizeof(modifiers) / sizeof(modifiers[0]));

    CGEventFlags flags = 0;

    for (size_t i = 0; i < modifierCount; i++) {
        flags |= modifiers[i].flag;

        if (!PostKeyboardEvent(source,
                               modifiers[i].keyCode,
                               YES,
                               flags)) {
            CFRelease(source);
            return NO;
        }
    }

    if (!PostKeyboardEvent(source, hotkey->keyCode, YES, hotkey->flags) ||
        !PostKeyboardEvent(source, hotkey->keyCode, NO, hotkey->flags)) {
        CFRelease(source);
        return NO;
    }

    for (size_t i = modifierCount; i > 0; i--) {
        ModifierKeyMapping mapping = modifiers[i - 1];
        flags &= ~mapping.flag;

        if (!PostKeyboardEvent(source,
                               mapping.keyCode,
                               NO,
                               flags)) {
            CFRelease(source);
            return NO;
        }
    }

    CFRelease(source);
    return YES;
}

static OSStatus SelectInputSourceWithWorkaround(TISInputSourceRef targetSource,
                                                CFArrayRef inputSources)
{
    if (targetSource == NULL) {
        return paramErr;
    }

    if (!InputSourceIsCJKV(targetSource)) {
        return TISSelectInputSource(targetSource);
    }

    NextInputSourceHotkey hotkey = {0};
    if (!ReadNextInputSourceHotkey(&hotkey)) {
        NSLog(@"[CJKHelper] Failed to read next input source hotkey. Fallback to direct select.");
        return TISSelectInputSource(targetSource);
    }

    TISInputSourceRef previousSource =
        CopyPreviousInputSource(inputSources, targetSource);

    if (previousSource == NULL) {
        NSLog(@"[CJKHelper] Failed to find previous input source. Fallback to direct select.");
        return TISSelectInputSource(targetSource);
    }

    OSStatus status = TISSelectInputSource(previousSource);
    CFRelease(previousSource);

    if (status != noErr) {
        NSLog(@"[CJKHelper] Failed to select previous input source. Error: %d",
              (int)status);
        return TISSelectInputSource(targetSource);
    }

    usleep(5000); // hack?
    
    if (!PostNextInputSourceShortcut(&hotkey)) {
        NSLog(@"[CJKHelper] Failed to post next input source shortcut. Fallback to direct select.");
        return TISSelectInputSource(targetSource);
    }

    return noErr;
}

@implementation CJKHelper

+ (OSStatus)selectNextInputSourceWithWorkaround
{
    NSAssert([NSThread isMainThread],
             @"CJKHelper must be called on the main thread.");

    CFArrayRef inputSources = CopySelectableKeyboardInputSources();
    if (inputSources == NULL) {
        NSLog(@"[CJKHelper] Failed to get input source list.");
        return kInputSourceError;
    }

    TISInputSourceRef currentSource = TISCopyCurrentKeyboardInputSource();
    if (currentSource == NULL) {
        NSLog(@"[CJKHelper] Failed to get current input source.");
        CFRelease(inputSources);
        return kInputSourceError;
    }

    TISInputSourceRef nextSource =
        CopyNextInputSource(inputSources, currentSource);

    CFRelease(currentSource);

    if (nextSource == NULL) {
        NSLog(@"[CJKHelper] No selectable input sources found.");
        CFRelease(inputSources);
        return kInputSourceError;
    }

    OSStatus status =
        SelectInputSourceWithWorkaround(nextSource, inputSources);

    CFRelease(nextSource);
    CFRelease(inputSources);

    return status;
}

@end
